### ISSUE TITLE
Use Email.js instead of formspree.

### ISSUE THREAD

**Issue by harshgupta20** [08mishra/prashantmishra#1]
In the contact-us page it would be good to use email.js since it gives more form submissions and also you can hide your keys.

**Comment by 08mishra** [comment]
Thanks for your valuable feedback Harsh! Surely I will look at it. By
the way how is my Portfolio website any rating or suggestions?

**Comment by harshgupta20** [comment]
Portfolio is good.
Suggestion : Hiding code-structure from the chrome dev tool, just apply .env file with Filemap to false.
